### ISSUE TITLE
Metamist timeouts killing pipelines

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#585]
e.g. https://batch.hail.populationgenomics.org.au/batches/431584

(I've seen this happen before, so the issue is based on that. For this linked batch I'm not sure if this correctly characterises the issue, as startup was fine, and every registration job has failed)

It looks like when metamist is overloaded (?) we see timeouts when either trying to start a pipeline run, or registering files following completion. Failing when registering output files is tricky, as the pipeline is written in such a way that an extant output file will prevent a stage being repeated, even if the output file isn't registered in the database - this leads to a gap in metamist that either needs to be filled manually, or by forcing a stage to re-run.

Pipeline side:
- Include some (more) repeat/backoff in the registration call?
- Upon failure dump the intended call into a temp file?
- Something tricky so that the pipeline can carry out just the registration step if the file exists

Metamist side:
- Bump metamist server resources?

**Comment by MattWellie** [comment]
Example traceback
```
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<string>", line 32, in <module>
  File "/cpg_workflows/status.py", line 73, in complete_analysis_job
    a_id = aapi.create_analysis(project=project_name, analysis=this_analysis)
  File "/usr/local/lib/python3.10/site-packages/metamist/api/analysis_api.py", line 773, in create_analysis
    return self.create_analysis_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/metamist/api_client.py", line 848, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/metamist/api_client.py", line 409, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/site-packages/metamist/api_client.py", line 203, in __call_api
    raise e
  File "/usr/local/lib/python3.10/site-packages/metamist/api_client.py", line 196, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.10/site-packages/metamist/api_client.py", line 463, in request
    return self.rest_client.PUT(url,
  File "/usr/local/lib/python3.10/site-packages/metamist/rest.py", line 276, in PUT
    return self.request("PUT", url,
  File "/usr/local/lib/python3.10/site-packages/metamist/rest.py", line 223, in request
    raise ServiceException(http_resp=r)
metamist.exceptions.ServiceException: (504)
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain', 'X-Cloud-Trace-Context': 'some-hash-here', 'Date': 'Fri, 05 Jan 2024 07:23:57 GMT', 'Server': 'Google Frontend', 'Content-Length': '24'})
HTTP response body: upstream request timeout
```

Theory - is this a real issue, or is this a service account for VCGS-clinical not being able to write this data?

**Comment by EddieLF** [comment]
@MattWellie I don't think that it's to do with the dataset's service account not having write permissions. In [this batch](https://batch.hail.populationgenomics.org.au/batches/431183) from 31/12/2023 about 2 weeks ago, the analysis entries for CRAMs and GVCFs of hundreds of sequencing groups were successfully written, e.g. [This sequencing group](https://batch.hail.populationgenomics.org.au/batches/431183/jobs/6).

```
Logs
Input
Log 
INFO:deploy_config:deploy config file found at /deploy-config/deploy-config.json
INFO:deploy_config:deploy config location: gce
INFO:hailtop.aiocloud.aiogoogle.credentials:using credentials file /gsa-key/key.json: GoogleServiceAccountCredentials for ...
Transfer summary:
  Transfers: 2
  Sources: 2
  Files: 2
  Bytes: 353 Bytes
  Time: 832ms
  Average bandwidth: 424 Bytes/s
  Average file rate: 2.4/s
Sources:
  .../batch-tmp/8df0d3/Register_analysis_output_gs___cpg-..._exome_cram_..._cram-wkdJ0/args/code0.p: 1 files, 292 Bytes
  .../batch-tmp/8df0d3/functions/code140113178622224.p: 1 files, 61 Bytes

Main
Log 
Created Analysis(id=..., type=cram, output=...) in vcgs-clinical
```

**Comment by MattWellie** [comment]
Awesome, thanks for digging that out @EddieLF

**Comment by illusional** [comment]
There were some issues from late last week with longer timeouts, and the metamist instance was hanging due to my incorrectly using a lock - this has now been resolved (https://github.com/populationgenomics/metamist/pull/642). I think persistence from production-pipelines is still a good call though.

**Comment by EddieLF** [comment]
I'm facing a similar issue, though not on the same scale. 

Across 119 genome sequencing groups, 4 failed to write an analysis entry from the Align stage. The four failed jobs can be seen [here](https://batch.hail.populationgenomics.org.au/batches/432380?q=state%3Dfailed). The log for each of the failed jobs is identical, it looks like the issue is around pulling the config out of temp storage? Kind of a bizarre thing to fail on. Were there too many VMs trying to download the config at the same time I wonder?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4332, in _prep_and_do_download
    self._do_download(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 987, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/download.py", line 237, in consume
    return _request_helpers.wait_and_retry(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 178, in wait_and_retry
    raise error
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/download.py", line 219, in retriable_request
    self._process_response(result)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_download.py", line 188, in _process_response
    _helpers.require_status_code(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 429, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 432, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/cpg_workflows/__init__.py", line 2, in <module>
    from cpg_utils.config import prepend_config_paths
  File "/usr/local/lib/python3.10/site-packages/cpg_utils/config.py", line 44, in <module>
    _validate_configs(_config_paths)
  File "/usr/local/lib/python3.10/site-packages/cpg_utils/config.py", line 32, in _validate_configs
    with p.open() as f:
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/cloudpath.py", line 552, in open
    self._refresh_cache(force_overwrite_from_cloud=force_overwrite_from_cloud)
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/cloudpath.py", line 1120, in _refresh_cache
    self.download_to(self._local)
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/cloudpath.py", line 893, in download_to
    return self.client._download_file(self, destination)
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/gs/gsclient.py", line 121, in _download_file
    blob.download_to_filename(local_path)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 1282, in download_to_filename
    self._handle_filename_and_download(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 1158, in _handle_filename_and_download
    self._prep_and_do_download(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4345, in _prep_and_do_download
    _raise_from_invalid_response(exc)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4791, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.TooManyRequests: 429 GET https://storage.googleapis.com/download/storage/v1/b/cpg-<dataset>-main-tmp/o/batch-tmp%2Fconfig%2Fa11161e8-da8a-43c9-ab4d-83d2491fb8fa.toml?generation=1706421660701956&alt=media: This workload is drawing too much egress bandwidth from Cloud Storage and has exceeded the GoogleEgressBandwidth Quota. This quota applies at a per-project per-region level to the egress bandwidth from buckets in regions and dual-regions to Google. Please reduce the rate of request. Refer to https://cloud.google.com/storage/quotas#bandwidth for more information.: ('Request failed with status code', 429, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4332, in _prep_and_do_download
    self._do_download(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 987, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/download.py", line 237, in consume
    return _request_helpers.wait_and_retry(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 178, in wait_and_retry
    raise error
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/download.py", line 219, in retriable_request
    self._process_response(result)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_download.py", line 188, in _process_response
    _helpers.require_status_code(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 429, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<string>", line 27, in <module>
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 432, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/cpg_workflows/__init__.py", line 2, in <module>
    from cpg_utils.config import prepend_config_paths
  File "/usr/local/lib/python3.10/site-packages/cpg_utils/config.py", line 44, in <module>
    _validate_configs(_config_paths)
  File "/usr/local/lib/python3.10/site-packages/cpg_utils/config.py", line 32, in _validate_configs
    with p.open() as f:
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/cloudpath.py", line 552, in open
    self._refresh_cache(force_overwrite_from_cloud=force_overwrite_from_cloud)
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/cloudpath.py", line 1120, in _refresh_cache
    self.download_to(self._local)
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/cloudpath.py", line 893, in download_to
    return self.client._download_file(self, destination)
  File "/usr/local/lib/python3.10/site-packages/cloudpathlib/gs/gsclient.py", line 121, in _download_file
    blob.download_to_filename(local_path)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 1282, in download_to_filename
    self._handle_filename_and_download(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 1158, in _handle_filename_and_download
    self._prep_and_do_download(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4345, in _prep_and_do_download
    _raise_from_invalid_response(exc)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4791, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.TooManyRequests: 429 GET https://storage.googleapis.com/download/storage/v1/b/cpg-<dataset>-main-tmp/o/batch-tmp%2Fconfig%2Fa11161e8-da8a-43c9-ab4d-83d2491fb8fa.toml?generation=1706421660701956&alt=media: This workload is drawing too much egress bandwidth from Cloud Storage and has exceeded the GoogleEgressBandwidth Quota. This quota applies at a per-project per-region level to the egress bandwidth from buckets in regions and dual-regions to Google. Please reduce the rate of request. Refer to https://cloud.google.com/storage/quotas#bandwidth for more information.: ('Request failed with status code', 429, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
```

**Comment by vivbak** [comment]
This was mostly handled in metamist, but there are still some production pipelines actions:
1- as matt suggested, wrap in a retry
2- In the case of failure, capture that pay-load so that we can populate analysis entries afterward. 
3- Come up with a solution for the 'metamist as source of truth' goal that doesn't make life harder when things fail.

**Comment by MattWellie** [comment]
This has now been doubly treated by retry wrappers, and @milo-hyben has a ticket in the Metamist project to treat at source (SET-220?)
